// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace test.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class BillingScedule
    {
        /// <summary>
        /// Initializes a new instance of the BillingScedule class.
        /// </summary>
        public BillingScedule() { }

        /// <summary>
        /// Initializes a new instance of the BillingScedule class.
        /// </summary>
        public BillingScedule(string id = default(string), string patientId = default(string), string procedureCodeId = default(string), string operationId = default(string), DateTime? date = default(DateTime?), bool? billed = default(bool?))
        {
            Id = id;
            PatientId = patientId;
            ProcedureCodeId = procedureCodeId;
            OperationId = operationId;
            Date = date;
            Billed = billed;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PatientId")]
        public string PatientId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ProcedureCodeId")]
        public string ProcedureCodeId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OperationId")]
        public string OperationId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Date")]
        public DateTime? Date { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Billed")]
        public bool? Billed { get; set; }

    }
}
