// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace test.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class EntityObject
    {
        /// <summary>
        /// Initializes a new instance of the EntityObject class.
        /// </summary>
        public EntityObject() { }

        /// <summary>
        /// Initializes a new instance of the EntityObject class.
        /// </summary>
        public EntityObject(IList<EntityObject> parents = default(IList<EntityObject>), object theObject = default(object), string objectTypeName = default(string))
        {
            Parents = parents;
            TheObject = theObject;
            ObjectTypeName = objectTypeName;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Parents")]
        public IList<EntityObject> Parents { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TheObject")]
        public object TheObject { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ObjectTypeName")]
        public string ObjectTypeName { get; set; }

    }
}
