// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace test.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class MedicalArtifact
    {
        /// <summary>
        /// Initializes a new instance of the MedicalArtifact class.
        /// </summary>
        public MedicalArtifact() { }

        /// <summary>
        /// Initializes a new instance of the MedicalArtifact class.
        /// </summary>
        public MedicalArtifact(string id = default(string), string name = default(string), string patientId = default(string), string typeId = default(string), DateTime? date = default(DateTime?), string blobId = default(string))
        {
            Id = id;
            Name = name;
            PatientId = patientId;
            TypeId = typeId;
            Date = date;
            BlobId = blobId;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PatientId")]
        public string PatientId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TypeId")]
        public string TypeId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Date")]
        public DateTime? Date { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BlobId")]
        public string BlobId { get; set; }

    }
}
