// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace test.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class OperationDetails
    {
        /// <summary>
        /// Initializes a new instance of the OperationDetails class.
        /// </summary>
        public OperationDetails() { }

        /// <summary>
        /// Initializes a new instance of the OperationDetails class.
        /// </summary>
        public OperationDetails(string id = default(string), string patientId = default(string), DateTime? date = default(DateTime?), string surgeonId = default(string), string assistant = default(string), string anaesthetist = default(string), string operationTypeId = default(string), string operationName = default(string), string position = default(string), string side = default(string), string technique = default(string), string findings = default(string), string woundClosure = default(string), string postOp = default(string))
        {
            Id = id;
            PatientId = patientId;
            Date = date;
            SurgeonId = surgeonId;
            Assistant = assistant;
            Anaesthetist = anaesthetist;
            OperationTypeId = operationTypeId;
            OperationName = operationName;
            Position = position;
            Side = side;
            Technique = technique;
            Findings = findings;
            WoundClosure = woundClosure;
            PostOp = postOp;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PatientId")]
        public string PatientId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Date")]
        public DateTime? Date { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SurgeonId")]
        public string SurgeonId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Assistant")]
        public string Assistant { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Anaesthetist")]
        public string Anaesthetist { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OperationTypeId")]
        public string OperationTypeId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OperationName")]
        public string OperationName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Position")]
        public string Position { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Side")]
        public string Side { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Technique")]
        public string Technique { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Findings")]
        public string Findings { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "WoundClosure")]
        public string WoundClosure { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PostOp")]
        public string PostOp { get; set; }

    }
}
