// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace test.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Patient
    {
        /// <summary>
        /// Initializes a new instance of the Patient class.
        /// </summary>
        public Patient() { }

        /// <summary>
        /// Initializes a new instance of the Patient class.
        /// </summary>
        public Patient(string id = default(string), string patientNo = default(string), string lastName = default(string), string firstName = default(string))
        {
            Id = id;
            PatientNo = patientNo;
            LastName = lastName;
            FirstName = firstName;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PatientNo")]
        public string PatientNo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LastName")]
        public string LastName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FirstName")]
        public string FirstName { get; set; }

    }
}
