// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace test.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class PatientEvent
    {
        /// <summary>
        /// Initializes a new instance of the PatientEvent class.
        /// </summary>
        public PatientEvent() { }

        /// <summary>
        /// Initializes a new instance of the PatientEvent class.
        /// </summary>
        public PatientEvent(string id = default(string), string patientId = default(string), DateTime? date = default(DateTime?), string description = default(string))
        {
            Id = id;
            PatientId = patientId;
            Date = date;
            Description = description;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PatientId")]
        public string PatientId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Date")]
        public DateTime? Date { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Description")]
        public string Description { get; set; }

    }
}
