// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace test.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class PersonalAssistant
    {
        /// <summary>
        /// Initializes a new instance of the PersonalAssistant class.
        /// </summary>
        public PersonalAssistant() { }

        /// <summary>
        /// Initializes a new instance of the PersonalAssistant class.
        /// </summary>
        public PersonalAssistant(string id = default(string), string practiceNo = default(string), string lastName = default(string), string firstName = default(string), string email = default(string))
        {
            Id = id;
            PracticeNo = practiceNo;
            LastName = lastName;
            FirstName = firstName;
            Email = email;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PracticeNo")]
        public string PracticeNo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LastName")]
        public string LastName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FirstName")]
        public string FirstName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Email")]
        public string Email { get; set; }

    }
}
